version: '3'

services:
  telegram-surveillance-bot:
    container_name: telegram-surveillance-bot
    image: telegram-surveillance-bot
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Mandatory variables
      - BOT_API_TOKEN
      - AUTHORIZED_USER
      # Optional variables
      - PERSISTENCE_DIR
      - LOG_LEVEL
      - BOT_LOG_LEVEL